services:
  postgres:
    container_name: gca-postgres
    image: postgres:16.3
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC
    volumes:
      - gca-postgres-data:/var/lib/postgresql/data

  swagger-ui:
    container_name: gca-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /mnt/swagger.yaml
    volumes:
      - ../../docs/swagger.yaml:/mnt/swagger.yaml:ro

volumes:
  gca-postgres-data:

